InputPaths: ../../input
Host: aconcavy.github.io
LinksUseHttps: true
LinkRoot: /blog
LinkLowercase: true
UseCache: false
DateTimeInputCulture: ja-JP
MirrorResources: true

GitHubOwner: AconCavy
GitHubName: blog
GitHubToken: => Config.FromSetting<string>("GITHUB_TOKEN")
GitHubBranch: gh-pages
