InputPaths: ../../input
Host: blog.aconcavy.dev
LinksUseHttps: true
LinkLowercase: true
UseCache: false
DateTimeInputCulture: ja-JP
DateTimeDisplayCulture: ja-JP
MirrorResources: true

GitHubOwner: AconCavy
GitHubName: blog
GitHubToken: => Config.FromSetting<string>("GITHUB_TOKEN")
GitHubBranch: gh-pages
