SiteTitle: acon.log
PageTitle: |
  =>
  {
    var siteTitle = Context.GetString("SiteTitle");
    var title = GetString("Title");
    return string.IsNullOrWhiteSpace(siteTitle) ? title : (string.IsNullOrWhiteSpace(title) ? siteTitle : $"{siteTitle} - {title}");
  }
PostSources: posts/*
IsPost: => Outputs.FilterSources(Context.GetString("PostSources")).ContainsById(Document)
Layout: /_layout.cshtml
Host: aconcavy.github.io
LinkRoot: /blog
LinksUseHttps: true
LinkLowercase: true
UseCache: false
DateTimeInputCulture: ja-JP

Copyright: => $"Copyright © 2020-{DateTime.Now.Year} AconCavy"

GitHubOwner: AconCavy
GitHubName: blog
GitHubToken: => Config.FromSetting<string>("GITHUB_TOKEN")
GitHubBranch: gh-pages
